# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Ivar Rydstrom
description: Ivar Rydstrom's Website
show_description: false
accent_image: assets/images/cryostat2.jpg
lang: en
keywords: [Ivar, Rydstrom, Physics, Computer Science, Research, SLAC, Stanford, Santa Clara, SCU, BlueFors, Oxford, Cryostat, LTD, Dark, Matter]
github_username: Ivar-Rydstrom
linkedin: ivar-rydstrom
author:
  name: Ivar Rydstrom
  email: irydstrom@scu.edu
copyright: © 2024 Ivar Rydstrom. All rights reserved.
favicon: assets/icons/favicon.ico

# Build settings
# theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-feed


custom-javascript-list: assets/scripts/onload.js

hydejack:
  no_drawer: false
  no_toc: false
  advertise: false

menu:
- title:             About
  url:               /about/
- title:             Research
  url:               /research/
- title:             Projects
  url:               /projects/
- title:             CV
  url:               /cv/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

